### PR TITLE
Adding support to splinter find_by_text

### PR DESCRIPTION
**Pull request by belimawr**
I added support to Splinter ´´find_by_text´´ method and updated Splinter version to `splinter>=0.7.3`.

### CODE REVIEW

**Comment by gabrielpjordao** [comment]
Thanks for the PR @belimawr! Sorry for the delay :-) 

I feel it would be a good idea to add a splinter specific test as well before merging this (at https://github.com/gabrielpjordao/pyfunct/blob/master/tests/contrib/test_splinter_driver.py).

Let me know if you have any questions.

**Comment by belimawr** [comment]
@gabrielpjordao, don't worry ;)

I added a splinter specific test.

**Comment by gabrielpjordao** [comment]
Thanks @belimawr!

**Comment by gabrielpjordao** [comment]
If you need me to bump a version for that, let me know!

**Pull request merged**
